### ISSUE TITLE
-i option isn't working

### ISSUE THREAD

**Issue by catfist** [ali-rantakari/trash#13]
(GNU bash 4.3.42)
(BSD rm January 28, 1999)

I can `rm` interactive with `-i` option, but it's not available with `trash`.

What `rm` option is really available with `trash` ?

**Comment by Arcank** [comment]
`-i` is just silently ignored: https://github.com/ali-rantakari/trash/blob/master/trash.m#L482

I don't think you need any of the `rm` options, that's one point of this tool :)

**Comment by ali-rantakari** [comment]
Yep, many `rm` options are accepted but ignored by design.

> What `rm` option is really available with `trash` ?

The `trash` man page and “usage” output should answer this question.
