### ISSUE TITLE
Incapable of installing via brew

### ISSUE THREAD

**Issue by BenLeggieroNCR** [ali-rantakari/trash#14]
Here's what I get:
http://pastebin.com/WjP1s4j5

**Comment by retornam** [comment]
@BenLeggieroNCR  which version of MacOS X are you running?

**Comment by BenLeggieroNCR** [comment]
@retornam OS X Yosemite - 10.10.5 (14F1021)

**Comment by retornam** [comment]
@BenLeggieroNCR please update your version of Xcode.

**Comment by BenLeggieroNCR** [comment]
@retornam done, didn't fix. http://pastebin.com/vLPMpPGY

**Comment by ohnit** [comment]
I had this problem too. I am running XCode 7.1.1 with the command line tools installed. I ran `brew doctor` and it gave me this message:
```
Warning: Xcode 7 lacks the 10.10 SDK which can cause some builds to fail.
We recommend installing the Command Line Tools with:
  xcode-select --install
to resolve this issue.
```

After running `xcode-select --install`, i was able to install via `brew install trash` with no problems.

**Comment by BenLeggieroNCR** [comment]
Thanks, @ohnit! That fixed it for me. Surprised nothing told me I needed to `xcode-select --install` first.
