### ISSUE TITLE
Mention install process in readme.md

### ISSUE THREAD

**Issue by jlevy** [ali-rantakari/trash#16]
Would it be possible to mention the brew install (and any other install) instructions on the readme here?

They appear at http://hasseg.org/trash/ but neither a link to that page nor the instructions are actually on the readme here.

I'd like to link to this repo from [this guide](https://github.com/jlevy/the-art-of-command-line) as it seems to be the best tool for the job, and prefer to link to GitHub repositories when possible.

Many thanks for a great program.

**Comment by certainlyakey** [comment]
Thanks for a great program! But also having installation instructions for those who doesn't have Macports or Brew like those given [here](http://hasseg.org/blog/post/406/trash-files-from-the-os-x-command-line/#comment-23184) would be nice.

**Comment by ali-rantakari** [comment]
Thanks for the heads up. The readme contains installation instructions now.
