### ISSUE TITLE
"Put back" seems to work after `trash -a`

### ISSUE THREAD

**Issue by aaronjensen** [ali-rantakari/trash#20]
I'm on El Capitan, and "Put back" appears to work after using `trash -a`. Is the comment old or does it apply to Sierra? Or am I special 😄 ?

Thanks for this util, it's super handy!

**Comment by ali-rantakari** [comment]
Since 0.9.0 `trash` uses the system API by default, although unfortunately “put back” still seems to require going through Finder (on High Sierra).
