### ISSUE TITLE
Add option to trash via Finder

### ISSUE THREAD

**Issue by vitorgalvao** [ali-rantakari/trash#21]
You recently made [trashing via the system API the default option](https://github.com/ali-rantakari/trash/commit/b530f17b51dfd9d210ec39b8653a7841fb0184b4). To me, asking the Finder to do the trashing always worked better, no exceptions. It seems that using the system API we (taken from [a post I made on another tool that made this same change](https://www.alfredforum.com/topic/9861-why-the-current-trashing-behaviour-fixed-33-b787-pre-release/#comment-49372), and ultimately reverted it):

+ **Gain** speed. I’m basing this on what I read on `trash`’s manual. I don’t see this as relevant, though, as I never had any complaints on the speed of Finder trashing items.
+ **Lose** the trashing sound. Small thing, but important to me. It’s more consistent with the rest of the OS’s usage.
+ **Lose** the “put back” feature. This is big. It essentially means we lose easy undo to trashing files. Depending on how many files we trashed and how many we already had there, this can make the difference between losing those files or not.
+ **Lose** stability. This is another big one. It is not unheard of that I delete something using the API and even though it is deleted, the Finder doesn't see it. This means my target can still be seen where it was and not be seen in the trash even though it is what happened. Basically, this system API seems buggy when interacting with the Finder.

It’s fine that you make trashing with the API the default. But could you please add a new flag (`-f`?) to force trashing from the Finder?

**Comment by ali-rantakari** [comment]
Thank you for the comment, and thanks for your patience. v0.9.1 adds `-F`.
