### ISSUE TITLE
Trashing broken symbolic link results in error

### ISSUE THREAD

**Issue by tjnycum** [ali-rantakari/trash#22]
Currently, if `foo` is a symbolic link to a non-existent target, `trash foo` results in a "path does not exist" error. When links aren't broken, trash acts on the links themselves rather than their targets. It should do the same when they're broken.

**Comment by CNG** [comment]
I had `rm` aliased to `trash` in my `~/.zshrc` and worked around this issue by changing the alias to a function:

    rm () { [[ -e ${1: -1} ]] && trash "$@" || /bin/rm "$@" }

You should be able to do something similar using the name `trash`. For example (if you are not aliasing `rm` to `trash`):

    trash () { [[ -e ${1: -1} ]] && /usr/local/bin/trash "$@" || rm "$@" }

**Comment by raxod502** [comment]
```zsh
if (( $+commands[trash] )); then
    function t {
        emulate -LR zsh
        for arg in "$@"; do
            if [[ -e $arg ]]; then
                trash -a $arg
            else
                rm $arg
            fi
        done
    }
fi
```
