### ISSUE TITLE
0.9.0 release tag

### ISSUE THREAD

**Issue by jbaum98** [ali-rantakari/trash#23]
There's a commit bumping the version number to `0.9.0` (634655d1e0e27609fc0901819b866afad289fbf0). Can you create a release tag for this release? It would be useful for trash to be added to `nixpkgs` (nixos/nixpkgs#25713).

**Comment by jerguslejko** [comment]
any updates on this?

**Comment by mistydemeo** [comment]
@ali-rantakari Just checking in. An official 0.9.0 tag would be very useful for us in Homebrew; we've had requests to update the formula. :)

**Comment by ali-rantakari** [comment]
Thanks for your reminders and patience — I have added the `v0.9.0` tag now.

**Comment by mistydemeo** [comment]
Thank you!
