### ISSUE TITLE
update readme.md w/ default change: Finder → System API

### ISSUE THREAD

**Issue by JBallin** [ali-rantakari/trash#25]
https://github.com/ali-rantakari/trash/commit/b530f17b51dfd9d210ec39b8653a7841fb0184b4

> Always use “system API” by default

https://github.com/ali-rantakari/trash/blob/master/readme.md

> By default, trash asks Finder to move the specified files/folders to the trash instead of calling the system API to do this because of the "put back" feature that only works when trashing files through Finder.

--

Explain reason behind switch in readme or commit amendment. Clarify "put back" compatibility.

**Comment by ali-rantakari** [comment]
Thanks for the comment. This is clarified in v0.9.1.

**Comment by JBallin** [comment]
You may want to update here too, http://hasseg.org/trash/

> ...trash asks Finder to move the specified files/folders to the trash **instead of calling the system API**

**Comment by FranklinYu** [comment]
Please update the website as @JBallin said. It has been very confusing.
