### ISSUE TITLE
latest releases don't appear on Homebrew

### ISSUE THREAD

**Issue by vsanthanam** [ali-rantakari/trash#29]
Is this intentional? Homebrew still installs at `.8.x` version

**Comment by ilovezfs** [comment]
@vsanthanam yes. Homebrew has blocked the release of 0.9.1 on

https://github.com/ali-rantakari/trash/issues/28
https://github.com/ali-rantakari/trash/issues/29

which need to be fixed first.

**Comment by ilovezfs** [comment]
make that https://github.com/ali-rantakari/trash/issues/27

**Comment by ali-rantakari** [comment]
Thanks for the reports. These should be fixed in v0.9.2.

**Comment by ilovezfs** [comment]
Perfect. Thanks @ali-rantakari! I have updated https://github.com/Homebrew/homebrew-core/pull/29787 to be for 0.9.2

**Comment by ilovezfs** [comment]
I've now shipped 0.9.2 in Homebrew.
https://github.com/Homebrew/homebrew-core/commit/31a62dd09f48d83e526601e2cec8be4d9c298cf5
https://github.com/Homebrew/homebrew-core/commit/352f645193cae79e31cbe88a83f85acc4b948177
