### ISSUE TITLE
trash returns -600 while logging on remotely

### ISSUE THREAD

**Issue by goiwai** [ali-rantakari/trash#4]
I am using the trash command as like: `alias rm='trash'`. It's really simple and useful, thank you very much for providing this software. Only thing I want to get a suggestion is how we can use the trash while remotely logging on. For example:

```
myhost$ ssh remote.host
remote$ trash path_to_file
trash: error -600
# this is not failed on console, or on remote-desktop.
```

I appreciate if you could give me some advices.

**Comment by westonganger** [comment]
Heres what I did

```
if test "x${SSH_CONNECTION+x}" = "xx"; then
    rm(){ 
      mv $1  ~/.Trash
    }
else
    alias rm='trash'
fi
```

**Comment by ali-rantakari** [comment]
You don't need a special build of `trash` anymore — just supply the `-a` argument and it will use the system API instead of asking Finder to do the trashing.

**Comment by ooopscc** [comment]
Please check if your Finder app is running. I encounter this error because I use PathFinder, and Finder is not running. Launch Finder and rerun `trash` will work.
