### ISSUE TITLE
trash -e doesn't work when using ZSH

### ISSUE THREAD

**Issue by cor** [ali-rantakari/trash#7]
trash <file> does work, however

**Comment by ketiko** [comment]
@CorPruijs Are you using oh-my-zsh with the [osx plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/osx/osx.plugin.zsh#L141-L156) I was having the same problem and found that it's overriding `trash` with a function.  

I removed that from my plugin list and now it works.

**Comment by vitorgalvao** [comment]
@ali-rantakari Looks like this issue can be closed.
